name: CI

on:
  - push
  - pull_request

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go version
          go get -v ./...
      - name: Test with coverage
        run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Uploade coverage to Codecov
        uses: codecov/codecov-action@v2
